### ISSUE TITLE
More stuff or how to integrate additional module

### ISSUE THREAD

**Issue by Haxprox** [pawadski/monitoring_exporter#1]
Like it, thanks for your efforts on it but having all those functions(modules) as they are, may ask you to describe the flow to follow the correct function(module) structure in order to add more metrics stuff inside?
I don't think whether I'm able to make a pull request on it since my case is really customizable and not looks as production-ready but anyway, it would be great to have a such description.

**Comment by pawadski** [comment]
Not sure I understand the question. Can you share what you are trying to do specifically?

**Comment by Haxprox** [comment]
Nothing yet I have but going to implement something like with SMART disk status and specific fields. Some exotic temperatures around the servers and probably status from other connected devices.
The question is how to do it correctly using existed code flow. Just to extend the current functions in order to get more metrics.
How the function should look like(arguments, return values)? What array must be filled up in order to switch it into the main code?

**Comment by pawadski** [comment]
I think I get you. Try copying this function into a separate **metrics_functionname** function:

```
#
# BEGIN filesystem usage
function metrics_filesystem {
    buffer=$(df -PT $filesystem_targets 2>/dev/null | grep -v '^Filesystem' | tr -s '\t' ' ')
    
    # Filesystem 1024-blocks Used Available Capacity Mounted on
    # /dev/mapper/cl-home 99533328 37320564 62212764 38% /
    buildMetric "filesystem_total_kbytes" "gauge" "From df"
    buildMetric "filesystem_used_kbytes" "gauge" "From df"
    buildMetric "filesystem_avail_kbytes" "gauge" "From df"
    buildMetric "filesystem_capacity_percent" "gauge" "From df"

    while read -r device fstype total used avail percent target; do 
        labels="{mountpoint=\"$target\",source=\"$device\",fstype=\"$fstype\"}"
        addMetricContent "filesystem_total_kbytes" "$labels $total"
        addMetricContent "filesystem_used_kbytes" "$labels $used"
        addMetricContent "filesystem_avail_kbytes" "$labels $avail"
        noPercentSign=$(echo "$percent" | sed 's,%,,g')
        addMetricContent "filesystem_capacity_percent" "$labels $noPercentSign"
    done <<< "$buffer"

    buildOutput
}
# END filesystem usage
```

The function buildMetric basically adds a metric to the collection, in this case the metric name is uptime_seconds_total, the type is "counter" and the help text is "System uptime".

The addMetricContent function is used to add the actual metric value and labels. Unfortunately there is no built-in handling for labels as an array as you can see here.

buildOutput is used to "convert" the metric arrays to Prometheus compatible output and is placed at the very end.

Once you have your function (the name must be preceded by **metrics_**, ie. metrics_myfunction), add it to the array at line 22:

`declare -a exporters=( myfunction ... )`

Instead of modifying this exporter you may be interested in creating your own workflow following this post: [Exporting Prometheus Metrics with Bash Scripts](https://apawel.me/exporting-prometheus-metrics-with-bash-scripts/)

**Comment by Haxprox** [comment]
Got it. More than helpful! 
Many thanks!

**Comment by pawadski** [comment]
Added to README in https://github.com/pawadski/monitoring_exporter/commit/26fec4953a0c8fee252478d149a67445c9ef539a
